### ISSUE TITLE
No funciona ` get_microdata`

### ISSUE THREAD

**Issue by gefero** [ropensci/eph#11]
En windows sucede esto...

`> base_2016t3 <-  get_microdata(year = 2016,trimester = 3,labels = FALSE)[['base_individual']]
trying URL 'https://github.com/rindec/data/raw/master/eph/individual/base_individual_2016T3.RDS'
Content type 'application/octet-stream' length 3541265 bytes (3.4 MB)
downloaded 3.4 MB

Error in readRDS(path) : error reading from connection`

**Comment by DiegoKoz** [comment]
esto sigue pasando? a mi me funciona

**Comment by gefero** [comment]
Sigo con ese problema... Reinstale y sigue pasando

**Comment by DiegoKoz** [comment]
ahh, acabo de ver algo raro en tu código. Ya no se descarga una lista con ambas bases, sino que se define la base por type. Proba con esto 

`base_individual <- get_microdata(year = 2016, trimester = 3,type='individual')`

**Comment by gefero** [comment]
Mismo problema...
-----------------------------------
Germán Rosati
https://gefero.github.io
-----------------------------------

**Comment by DiegoKoz** [comment]
Sólo con los RDS de esta librería no? 
En qué SO?
La función 1° descarga la base en un archivo temporal, y después lo lee. Te podés fijar si el archivo se guarda bien? (tiene que estar en un directorio al lado de hacer `tempfile()`. 
Si el archivo esta ahí, fijate que sucede cuando tratas de levantarlo a mano, y si falla, fijate si agregandole la extensión RDS lo podés leer.

**Comment by gefero** [comment]
Es Windoes...
Paso esta instrucción
readRDS('C:/Users/grosati/AppData/Local/Temp/Rtmp06xQdK/file27fc93c37d3.RDS')

y me salta

Error in
readRDS("C:/Users/grosati/AppData/Local/Temp/Rtmp06xQdK/file27fc93c37d3.RDS")
:
  error reading from connection
-----------------------------------
Germán Rosati
https://gefero.github.io
-----------------------------------

**Comment by DiegoKoz** [comment]
mm, puede ser un tema de permisos en windows imagino. 

Modifiqué la función para que descargué directamente el RDS sin pasar por temp.

**Comment by pablotis** [comment]
Germán, te sigue apareciendo el mismo error? 

Probaste copiar la función y correrla localmente? 

Si no, fijate de instalar nuevamente la librería, me supo pasar lo mismo en computadoras con permisos limitados, ahora me funciona.

**Comment by pablotis** [comment]
get_microdata reparado y funcionando nuevamente, cierro issue.
