### ISSUE TITLE
error en "get_microdata_internal" Version: 0.3.0

### ISSUE THREAD

**Issue by PabloEzequielA** [ropensci/eph#19]
Al ejecutar las lineas que usaba el año pasado me encontré con este error que muestro para un trimestre a modo de ejemplo:
"
> library(eph)
> library(tidyverse)
> base_2019t2_ind <- get_microdata(year = 2019, trimester = 2, type = 'individual', vars = 'all')
Warning message:
In get_microdata(year = 2019, trimester = 2, type = "individual",  :
  No se pudo descargar la base de year 2019,trimester 2, wave NA, type individual.
Mensaje: problema con la descarga. Posiblemente un error de la conexion a internet
> base_2019t3_ind <- get_microdata(year = 2019, trimester = 3, type = 'individual', vars = 'all') 
probando la URL 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_3_Trim_2019_txt.zip'
Content type 'application/x-zip-compressed' length 3000521 bytes (2.9 MB)
"
Observé que no se presenta para el trimestre 2019t3 porque no lo descarga de "https://github.com/holatam/data".

**Comment by DiegoKoz** [comment]
Buenas!

Perdón por tardar en responder, no me llego notificación del mensaje. Acabo de probar 
`base_2019t2_ind <- get_microdata(year = 2019, trimester = 2, type = 'individual', vars = 'all')
` y me funciona. También para la última base del INDEC (trimestre 4, solo en la página de INDEC aún)

seguís teniendo el error? la conexión a internet funciona bien al momento de correr la función ?

**Comment by DiegoKoz** [comment]
Entiendo que esto esta resuelto. Si sigue fallando, @PabloEzequielA, por favor re abrí el issue
