### ISSUE TITLE
get_data 'hogar' no funcionando

### ISSUE THREAD

**Issue by jmacaggi** [ropensci/eph#21]
Hola!
Estaba intentando bajar la base para hogares y no me está dejando para todos los trimestres. Me baja con 0 rows. Estoy usando el siguiente código:

library("tidyverse")
library("eph")
library("np")
library("kdensity")
vars <- c('IPCF', 'COMPONENTE','ANO4', 'REGION',
          'TRIMESTRE','CH04','CH06',
          'ESTADO','PONDERA', 'AGLOMERADO')

data_4Q14 <- get_microdata(year = 2014, trimester = 4,
                          type= 'hogar', vars = vars)

Error:

2: In get_microdata(year = 2014, trimester = 4, type = "hogar", vars = vars) :
  No se pudo descargar la base de year 2014,trimester 4, wave NA, type hogar.
Mensaje:

**Comment by DiegoKoz** [comment]
hola @jmacaggi , el problema es que varias de las variables que le estas pidiendo a la base hogar están únicamente en la base individual. Por ejemplo _componente_ _ch04_ _ch06_ y _estado_. Si probas el siguiente código, funciona correctamente. 

`data_4Q14 <- get_microdata(year = 2014, trimester = 4, type= 'hogar')`

De todas formas, la función debería tener un mensaje de error más claro de qué es lo que sucede. Vamos a agregarlo.

Saludos

**Comment by DiegoKoz** [comment]
Agregado en https://github.com/holatam/eph/commit/e0824d0f6efcf8f8261a2f3899ee3cfdc7f7860a
