### ISSUE TITLE
Consulta labels CH15_COD

### ISSUE THREAD

**Issue by JuanPrimosich** [ropensci/eph#24]
Alguien los tiene? No los encuentro

**Comment by DiegoKoz** [comment]
@pablotis corregime si me equivoco, pero CH15_COD tiene lo siguiente:
 
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/28060531/93568561-a2ca5f80-f990-11ea-9d64-a74e4af4cc8f.png">

Osea es una combinación de varios códigos

Con la función  `organize labels` podes etiquetar esta variable. 

<img width="1317" alt="image" src="https://user-images.githubusercontent.com/28060531/93568812-02286f80-f991-11ea-9110-e2d01889377f.png">

Y si querés los diccionarios, imagino que se encuentran acá [https://sitioanterior.indec.gob.ar/nivel4_default.asp?id_tema_1=1&id_tema_2=39&id_tema_3=121](https://sitioanterior.indec.gob.ar/nivel4_default.asp?id_tema_1=1&id_tema_2=39&id_tema_3=121)

**Comment by JuanPrimosich** [comment]
Gracias Diego!! No encontraba los códigos y esa forma de combinar no lo
hice y me viene perfecto! Gracias mil!!
ᐧ
