### ISSUE TITLE
Dificultades para abrir bases de datos

### ISSUE THREAD

**Issue by Azulchinca** [ropensci/eph#30]
Hola!
Estoy teniendo un problema para abrir las eph.
Utilizo los siguientes códigos para abrir las bases de eph con las variables en var.ind

var.ind <- c('CODUSU','NRO_HOGAR' ,'COMPONENTE','ANO4','TRIMESTRE','REGION',
             'AGLOMERADO', 'PONDERA', 'CH04', 'CH06', 'ITF', 'PONDIH','P21')

bases <- get_microdata(year = 2016:2020,
                       trimester = 1:4,
                       type =  "individual",
                       vars = var.ind)

Y luego las uno...
bases <- bases %>% 
  unnest(cols = c(microdata))

Una vez unidas las bases, no me aparece la variable "AGLOMERADO" que es clave para mi análisis. No entiendo por qué sucede esto.

Les agradecería su respueta!

**Comment by DiegoKoz** [comment]
Buenas!

Corro lo siguiente

```
library(eph)
library(tidyverse)

var.ind <- c('CODUSU','NRO_HOGAR' ,'COMPONENTE','ANO4','TRIMESTRE','REGION',
             'AGLOMERADO', 'PONDERA', 'CH04', 'CH06', 'ITF', 'PONDIH','P21')

bases <- get_microdata(year = 2016:2020,
                       trimester = 1:4,
                       type = "individual",
                       vars = var.ind)
 
bases %>% 
  unnest(cols = c(microdata))
```
Y obtengo
![image](https://user-images.githubusercontent.com/28060531/119833580-827b7900-beff-11eb-8a80-ccb8fb1aec7e.png)


Pareciera estar todo ok, no? 
Te sigue pasando el error? qué versión del paquete tenes? (` packageVersion("eph")`)

saludos

**Comment by pablotis** [comment]
Cierro issue @Azulchinca. Avisanos si vuelve a surgir el error!
