### ISSUE TITLE
Calidad de la vivienda

### ISSUE THREAD

**Issue by enadianet** [ropensci/eph#31]
Hola, estoy viendo algunos ejemplos para trabajar con el paquete eph y no encuentro nada para trabajar sobre calidad de los materiales de la vivienda.
En los microdatos de EPH hay dos variables que son indicadores de la calidad de materiales de la vivienda, las cuales son: IV3, V4 y IV5. Según las categorías que toman estas variables quisiera generar una columna que me diga si la calidad es SUFICIENTE, PARCIALMENTE INSUFICIENTE o INSUFICIENTE.
A modo de ejemplo
si IV3 = 1 ,  V4= 1 ; IV5 = 1 , entonces la nueva variable (digamos calidad) será calidad = SUFICIENTE
   IV3 = 2 , V4 = 1 ; IV5 = 2.  entonces la nueva variable (digamos calidad) será calidad = INSUFICIENTE

Y así según las combinaciones posibles de estas tres variables.
Podría ayudarme con los comandos que debo usar? estoy trabajando con 4T 2020.
Muchas gracias.

**Comment by DiegoKoz** [comment]
Hola @enadianet , 

Se me ocurren dos opciones. una es usar el comando `case_when`
https://dplyr.tidyverse.org/reference/case_when.html

por ejemplo

```
df %>%
mutate(calidad_vivienda = case_when(IV3 == 1 & V4 ==  1 & IV5 = 1 ~ "suficiente",
                                                                  IV3 == 2 & V4 ==  1 & IV5 = 1 ~ "insuficiente",
                                                                  ....
```

Si hay muchas combinaciones eso puede ser medio tedioso, y quizas por reproducibilidad prefieras tener un archivo aparte (un excel) donde haces la codificacion, y luego con un left_join agregar las categorías nuevas


Saludos y espero que sirva

```

**Comment by enadianet** [comment]
Excelente Diego, voy a probar con esa primera opción.
Muchas gracias!!
