### ISSUE TITLE
Filtrar datos de hogares a personas

### ISSUE THREAD

**Issue by enadianet** [ropensci/eph#33]
Hola, estoy trabajando con la base de hogares y con Excel he seleccionado todos los CODUSU que cumplan con alguna condición, digamos, los que son inquilinos y esa lista de CONSUDU tiene por ejemplo 2500 filas. Ahora, quiero filtrar de la base de INDIVIDUOS todos esos CODUSU, para saber a cuántas personas inquilinas representan. Entonces no se como filtrar, las opciones que encontré te dan la posibilidad de filtrar pero hay que indicar uno a uno las condiciones, en este caso tengo 2500 de ellas. gRACIAS

**Comment by DiegoKoz** [comment]
Esta pregunta esta repetida no?
