### ISSUE TITLE
pasar de hogares a personas

### ISSUE THREAD

**Issue by enadianet** [ropensci/eph#34]
Hola, estoy trabajando con la base de hogares y con Excel he seleccionado todos los CODUSU que cumplan con alguna condición, digamos, los que son inquilinos y esa lista de CONSUDU tiene por ejemplo 2500 filas. Ahora, quiero filtrar de la base de INDIVIDUOS todos esos CODUSU, para saber a cuántas personas inquilinas representan. Entonces no se como filtrar, las opciones que encontré te dan la posibilidad de filtrar pero hay que indicar uno a uno las condiciones, en este caso tengo 2500 de ellas. gRACIAS

**Comment by DiegoKoz** [comment]
Hola.

Suena como que lo que queres hacer no necesita un filtro a mano en el
excel... quizás podes filtrar por esas condiciones directamente en R

Si tenes una lista de id, siempre podes filtrar la base con

DF %>% filter ( id %in% vector_de_ids)


Pero esto es algo más general de tidyverse  quizás te convenga revisar las
notas de as algún curso

Acá te dejo las notas de los cursos que arme por si sirven

https://sites.google.com/view/diego-kozlowski/teaching

Saludos

**Comment by enadianet** [comment]
Gracias Diego por tu pronta respuesta, como siempre.
Estoy probando con lo que me dijiste, pero no encuentra ninguna coincidencia en la lista, pero veo que hay un problema con la base original, creo que tiene que ver con los caracteres o algo así. Pero te pregunto, la lista original DF, la variable id y el vector a partir del cual querés filtrar,deben tener algún formato especial? o sea, deben ser todos vectores? en ese caso cómo hago para transformar una columna de una DF que abrí con read_excel sea un vector? probé con as.factor (DF, id) pero da lo mismo

**Comment by DiegoKoz** [comment]
es difícil sin un ejemplo reproducible. Los formatos de ambas variables deberían ser los mismos, pero un vector no es un formato. 

Quizás te conviene sumarte al slack de RenBaires: https://renbaires.github.io/ que hay más gente para responder este tipo de preguntas, que exceden al paquete de EPH

saludos

**Comment by enadianet** [comment]
Gracias Diego, ya lo tengo casi resuelto, voy a entrar en el slack de RenBaires. 
Tenés el link del curso del paquete de EPH que hicieron?

**Comment by DiegoKoz** [comment]
@pablotis y @Guidowe están dando los últimos cursos. Yo tengo esta versión, que es algo vieja (pre paquete eph) https://diegokoz.github.io/Curso_R_EPH_clases// 

saludos

**Comment by enadianet** [comment]
Gracias Diego
