### ISSUE TITLE
R - get_bases_eph a través de un proxy en Windows

### ISSUE THREAD

**Issue by martinweingart** [ropensci/eph#7]
En el caso que se quiera bajar las bases de eph en Windows a través de un proxy encontré necesario utilizar mode='libcurl' en utils.download.

**Comment by DiegoKoz** [comment]
gracias! lo estamos revisando. A algunes les funciona bien con así como estaba, a otres les funciona bien con `method='libcurl'` pero a otres les falló. Supongo que es un tema de dependencias y qué librerías tiene cada uno instaladas previamente

**Comment by DiegoKoz** [comment]
@pablinte  vos podrías chequear si ahora funciona esto así cerramos el issue?

**Comment by DiegoKoz** [comment]
Entiendo que esto ya esta resuelto. @martinweingart por favor avisanos si persiste el problema cuando queres usar el default. 

cierro el issue
